import React, { Component } from 'react';
import { Redirect, NavLink, withRouter } from 'react-router-dom';
import { connect } from 'react-redux';

import Toolbar from '../../components/navigation/toolbar/toolbar'

export class LandingPage extends Component {
   constructor(props) {
      super(props);
      this.state = {

      }
   }

   componentDidMount(){

   }

   render(){
      return(
         <div>
            <Toolbar />
            <div className="landing-page-content">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec feugiat nisl pretium fusce id velit. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Tortor consequat id porta nibh venenatis cras. Sapien faucibus et molestie ac feugiat sed. Pharetra et ultrices neque ornare aenean euismod. Felis eget nunc lobortis mattis aliquam faucibus purus in. Feugiat pretium nibh ipsum consequat. Purus ut faucibus pulvinar elementum integer. Porta lorem mollis aliquam ut porttitor. Purus in massa tempor nec feugiat nisl pretium fusce. Odio eu feugiat pretium nibh ipsum. Sed id semper risus in hendrerit gravida rutrum quisque. Praesent tristique magna sit amet. Tincidunt dui ut ornare lectus sit amet est placerat in. In massa tempor nec feugiat. Tristique et egestas quis ipsum suspendisse ultrices gravida. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor.

Dolor sed viverra ipsum nunc aliquet bibendum enim. Eget duis at tellus at urna condimentum mattis pellentesque. Lectus mauris ultrices eros in cursus turpis massa. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Scelerisque purus semper eget duis at tellus at. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Morbi leo urna molestie at elementum eu facilisis. Risus pretium quam vulputate dignissim. Condimentum lacinia quis vel eros. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Id porta nibh venenatis cras sed felis eget velit aliquet. Quam elementum pulvinar etiam non quam. Dolor purus non enim praesent elementum facilisis leo.

Quam nulla porttitor massa id neque aliquam vestibulum. Varius sit amet mattis vulputate enim. Etiam tempor orci eu lobortis elementum nibh. Et magnis dis parturient montes nascetur. Cursus mattis molestie a iaculis at. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Ultricies integer quis auctor elit. Id faucibus nisl tincidunt eget nullam non nisi est. Commodo nulla facilisi nullam vehicula ipsum a. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent.

Id porta nibh venenatis cras sed. Luctus accumsan tortor posuere ac. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Quam nulla porttitor massa id neque aliquam vestibulum. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Ultrices neque ornare aenean euismod. Accumsan in nisl nisi scelerisque eu ultrices vitae. Sit amet aliquam id diam. Nam at lectus urna duis convallis convallis tellus. Pellentesque sit amet porttitor eget dolor morbi. Ultricies mi quis hendrerit dolor. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Et pharetra pharetra massa massa ultricies. Magna sit amet purus gravida quis blandit turpis cursus in. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla.

Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Sagittis purus sit amet volutpat. Quisque sagittis purus sit amet volutpat. Phasellus vestibulum lorem sed risus. Et malesuada fames ac turpis egestas sed tempus. Ut tristique et egestas quis. Est ante in nibh mauris cursus mattis. Neque egestas congue quisque egestas diam in arcu. Sit amet nisl purus in mollis nunc sed id semper. Urna neque viverra justo nec ultrices dui sapien eget. Urna neque viverra justo nec ultrices dui. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Vehicula ipsum a arcu cursus vitae congue mauris. Arcu felis bibendum ut tristique et egestas quis. Sed nisi lacus sed viverra.

Turpis cursus in hac habitasse platea dictumst quisque sagittis. Diam sollicitudin tempor id eu nisl. Amet dictum sit amet justo donec enim diam vulputate. Vitae congue mauris rhoncus aenean vel elit scelerisque. Tempor orci dapibus ultrices in iaculis nunc sed. Accumsan tortor posuere ac ut consequat semper. Diam vel quam elementum pulvinar etiam non. Id diam maecenas ultricies mi eget mauris pharetra et. Lacus sed viverra tellus in hac habitasse platea dictumst. Elit at imperdiet dui accumsan sit amet nulla. Eget mauris pharetra et ultrices neque ornare aenean.

Iaculis urna id volutpat lacus laoreet non. Ut sem nulla pharetra diam. Dignissim sodales ut eu sem. Nam at lectus urna duis convallis convallis. Feugiat nisl pretium fusce id velit ut tortor. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Erat velit scelerisque in dictum non consectetur. Et malesuada fames ac turpis. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Mollis aliquam ut porttitor leo a diam sollicitudin. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Dignissim sodales ut eu sem integer.

Aliquam etiam erat velit scelerisque in dictum. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Vitae justo eget magna fermentum iaculis eu non diam. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. In aliquam sem fringilla ut morbi tincidunt. Iaculis nunc sed augue lacus viverra. In metus vulputate eu scelerisque felis imperdiet proin. Ut ornare lectus sit amet est. Netus et malesuada fames ac turpis egestas integer eget. Felis eget nunc lobortis mattis. Amet porttitor eget dolor morbi non arcu risus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Eu mi bibendum neque egestas congue quisque egestas.

Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Quis lectus nulla at volutpat diam ut venenatis. Nisl nunc mi ipsum faucibus. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Sit amet volutpat consequat mauris nunc congue. Dictumst quisque sagittis purus sit amet volutpat consequat. Viverra ipsum nunc aliquet bibendum. Integer quis auctor elit sed vulputate mi sit amet mauris. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Cursus in hac habitasse platea dictumst quisque sagittis purus.

Ornare massa eget egestas purus viverra. Sed augue lacus viverra vitae congue eu consequat ac. Lectus proin nibh nisl condimentum id venenatis a condimentum. Pharetra magna ac placerat vestibulum lectus mauris. Gravida neque convallis a cras semper auctor. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Luctus accumsan tortor posuere ac ut consequat. In hac habitasse platea dictumst quisque sagittis purus sit amet. Ac turpis egestas integer eget aliquet nibh praesent tristique. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Vitae tortor condimentum lacinia quis vel eros. Libero enim sed faucibus turpis. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Dignissim sodales ut eu sem integer vitae.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec feugiat nisl pretium fusce id velit. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Tortor consequat id porta nibh venenatis cras. Sapien faucibus et molestie ac feugiat sed. Pharetra et ultrices neque ornare aenean euismod. Felis eget nunc lobortis mattis aliquam faucibus purus in. Feugiat pretium nibh ipsum consequat. Purus ut faucibus pulvinar elementum integer. Porta lorem mollis aliquam ut porttitor. Purus in massa tempor nec feugiat nisl pretium fusce. Odio eu feugiat pretium nibh ipsum. Sed id semper risus in hendrerit gravida rutrum quisque. Praesent tristique magna sit amet. Tincidunt dui ut ornare lectus sit amet est placerat in. In massa tempor nec feugiat. Tristique et egestas quis ipsum suspendisse ultrices gravida. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor.

Dolor sed viverra ipsum nunc aliquet bibendum enim. Eget duis at tellus at urna condimentum mattis pellentesque. Lectus mauris ultrices eros in cursus turpis massa. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Scelerisque purus semper eget duis at tellus at. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Morbi leo urna molestie at elementum eu facilisis. Risus pretium quam vulputate dignissim. Condimentum lacinia quis vel eros. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Id porta nibh venenatis cras sed felis eget velit aliquet. Quam elementum pulvinar etiam non quam. Dolor purus non enim praesent elementum facilisis leo.

Quam nulla porttitor massa id neque aliquam vestibulum. Varius sit amet mattis vulputate enim. Etiam tempor orci eu lobortis elementum nibh. Et magnis dis parturient montes nascetur. Cursus mattis molestie a iaculis at. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Ultricies integer quis auctor elit. Id faucibus nisl tincidunt eget nullam non nisi est. Commodo nulla facilisi nullam vehicula ipsum a. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent.

Id porta nibh venenatis cras sed. Luctus accumsan tortor posuere ac. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Quam nulla porttitor massa id neque aliquam vestibulum. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Ultrices neque ornare aenean euismod. Accumsan in nisl nisi scelerisque eu ultrices vitae. Sit amet aliquam id diam. Nam at lectus urna duis convallis convallis tellus. Pellentesque sit amet porttitor eget dolor morbi. Ultricies mi quis hendrerit dolor. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Et pharetra pharetra massa massa ultricies. Magna sit amet purus gravida quis blandit turpis cursus in. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla.

Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Sagittis purus sit amet volutpat. Quisque sagittis purus sit amet volutpat. Phasellus vestibulum lorem sed risus. Et malesuada fames ac turpis egestas sed tempus. Ut tristique et egestas quis. Est ante in nibh mauris cursus mattis. Neque egestas congue quisque egestas diam in arcu. Sit amet nisl purus in mollis nunc sed id semper. Urna neque viverra justo nec ultrices dui sapien eget. Urna neque viverra justo nec ultrices dui. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Vehicula ipsum a arcu cursus vitae congue mauris. Arcu felis bibendum ut tristique et egestas quis. Sed nisi lacus sed viverra.

Turpis cursus in hac habitasse platea dictumst quisque sagittis. Diam sollicitudin tempor id eu nisl. Amet dictum sit amet justo donec enim diam vulputate. Vitae congue mauris rhoncus aenean vel elit scelerisque. Tempor orci dapibus ultrices in iaculis nunc sed. Accumsan tortor posuere ac ut consequat semper. Diam vel quam elementum pulvinar etiam non. Id diam maecenas ultricies mi eget mauris pharetra et. Lacus sed viverra tellus in hac habitasse platea dictumst. Elit at imperdiet dui accumsan sit amet nulla. Eget mauris pharetra et ultrices neque ornare aenean.

Iaculis urna id volutpat lacus laoreet non. Ut sem nulla pharetra diam. Dignissim sodales ut eu sem. Nam at lectus urna duis convallis convallis. Feugiat nisl pretium fusce id velit ut tortor. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Erat velit scelerisque in dictum non consectetur. Et malesuada fames ac turpis. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Mollis aliquam ut porttitor leo a diam sollicitudin. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Dignissim sodales ut eu sem integer.

Aliquam etiam erat velit scelerisque in dictum. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Vitae justo eget magna fermentum iaculis eu non diam. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. In aliquam sem fringilla ut morbi tincidunt. Iaculis nunc sed augue lacus viverra. In metus vulputate eu scelerisque felis imperdiet proin. Ut ornare lectus sit amet est. Netus et malesuada fames ac turpis egestas integer eget. Felis eget nunc lobortis mattis. Amet porttitor eget dolor morbi non arcu risus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Eu mi bibendum neque egestas congue quisque egestas.

Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Quis lectus nulla at volutpat diam ut venenatis. Nisl nunc mi ipsum faucibus. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Sit amet volutpat consequat mauris nunc congue. Dictumst quisque sagittis purus sit amet volutpat consequat. Viverra ipsum nunc aliquet bibendum. Integer quis auctor elit sed vulputate mi sit amet mauris. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Cursus in hac habitasse platea dictumst quisque sagittis purus.

Ornare massa eget egestas purus viverra. Sed augue lacus viverra vitae congue eu consequat ac. Lectus proin nibh nisl condimentum id venenatis a condimentum. Pharetra magna ac placerat vestibulum lectus mauris. Gravida neque convallis a cras semper auctor. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Luctus accumsan tortor posuere ac ut consequat. In hac habitasse platea dictumst quisque sagittis purus sit amet. Ac turpis egestas integer eget aliquet nibh praesent tristique. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Vitae tortor condimentum lacinia quis vel eros. Libero enim sed faucibus turpis. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Dignissim sodales ut eu sem integer vitae.
            </div>
         </div>
      )
   }

}

export default LandingPage;